### PR TITLE
Updated version of uvcov.py.

### PR DESCRIPTION
**Pull request by petschow**
Replaced PGPlot by matplotlib, replaced optparse by argparse, and added some other minor updates to the code (arguments etc.).

### CODE REVIEW

**Comment by tammojan** [comment]
Thanks a lot for this!

**Comment by tammojan** [comment]
Hi @petschow, your code has some issues, could you make a new PR with these issues fixed? In particular, the options `inms` and `filename` were renamed, but the main function doesn't know that yet.

**Comment by ygrange** [comment]
Whoops. Pull request to the pull request submitted!

**Comment by petschow** [comment]
Of course, it is always the last second changes before the pull request. :) Just quickly rename the arguments ('--output' was requested, instead of '--filename'), then why not use '--input' for consistency then... and then... not checking the changes. Is it working correctly now?

**Comment by tammojan** [comment]
Could you make a new Pull Request?

**Comment by petschow** [comment]
Done. But I am not sure, if it worked as I intended.

**Comment by tammojan** [comment]
I'll test it in cep3.

**Pull request merged**
